#!/bin/sh
# Generates Secrets.swift from Xcode Cloud environment variables.
# Set these in App Store Connect → Xcode Cloud → your workflow → Environment.

set -e

cat > "${CI_PRIMARY_REPOSITORY_PATH}/fynch/Secrets.swift" <<EOF
// Auto-generated by ci_post_clone.sh — do not edit
enum Secrets {
    static let tmdbBearerToken = "${TMDB_BEARER_TOKEN}"
}

enum FirebaseConfig {
    static let apiKey    = "${FIREBASE_API_KEY}"
    static let projectId = "${FIREBASE_PROJECT_ID}"
}
EOF

echo "Secrets.swift generated."
